# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/ (optional)
url: "http://{username}.github.io" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Jason Clegg # Your name will go here
  description: "Born to code... just didn't realize it until I was 34..." # used by search engines

  # Header and footer text
  header_text: >
     <h1>Wannabe Software Developer (nay.. Engineer!!!)</h1>
     <p>After thirteen years, I am switching back into where my natural talent lies. I am learning to code, and hoping to become a Software Developer </p>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> and made with blood, sweat, tears (and a lot of cheese and sausage).

  # Icons
  rss: false
  email_address: "jgcdeveloper@gmail.com"
  behance:
  bitbucket:
  dribbble:
  facebook: jasongc
  flickr:
  github: jgcdeveloper
  google_plus:
  instagram:
  linkedin:  "https://www.linkedin.com/in/jason-clegg-37739422"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  "https://stackoverflow.com/users/6799064/jgc-developer"
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-85085591-1"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Read more &raquo;"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Lato:300,400,700,300italic,700italic|Abril+Fatface"

# PAGINATION
paginate: 12
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# BUILD SETTINGS
markdown: kramdown

sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate]
